"""initial schema

Revision ID: 2a9ae8467581
Revises: 
Create Date: 2026-09-04 08:05:31.550654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision: str = '2a9ae8467581'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('computers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('computer_key', sa.String(length=64), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_host', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('computer_key')
    )
    op.create_table('physical_devices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hardware_stable_sha256', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('identity_confidence', sa.String(length=32), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('representative_device', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_physical_devices_hardware_stable_sha256'), 'physical_devices', ['hardware_stable_sha256'], unique=False)
    op.create_table('agents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('computer_id', sa.Uuid(), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('agent_version', sa.String(length=64), nullable=False),
    sa.Column('current_ips', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('queue_size', sa.Integer(), nullable=False),
    sa.Column('selected_route', sa.String(length=32), nullable=False),
    sa.Column('proxy_id', sa.Uuid(), nullable=True),
    sa.Column('source_ip', sa.String(length=128), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=True),
    sa.Column('enroll_source_ip', sa.String(length=128), nullable=True),
    sa.Column('enrolled_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['computer_id'], ['computers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_computer_id'), 'agents', ['computer_id'], unique=False)
    op.create_index(op.f('ix_agents_last_seen_at_utc'), 'agents', ['last_seen_at_utc'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('source_ip', sa.String(length=128), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_action', 'audit_log', ['action'], unique=False)
    op.create_index('ix_audit_log_created_at', 'audit_log', ['created_at_utc'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_ip', sa.String(length=128), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_auth_sessions_expires_at_utc'), 'auth_sessions', ['expires_at_utc'], unique=False)
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('media_states',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('physical_device_id', sa.Uuid(), nullable=False),
    sa.Column('media_identity_sha256', sa.String(length=64), nullable=True),
    sa.Column('media_state_sha256', sa.String(length=64), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('representative_media', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['physical_device_id'], ['physical_devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('physical_device_id', 'media_identity_sha256', 'media_state_sha256', name='uq_media_state_device_hashes')
    )
    op.create_index(op.f('ix_media_states_physical_device_id'), 'media_states', ['physical_device_id'], unique=False)
    op.create_table('observations',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('probe_version', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('observed_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at_utc', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('user_sid', sa.String(length=255), nullable=True),
    sa.Column('hardware_stable_sha256', sa.String(length=64), nullable=True),
    sa.Column('pnp_observation_sha256', sa.String(length=64), nullable=True),
    sa.Column('media_identity_sha256', sa.String(length=64), nullable=True),
    sa.Column('media_state_sha256', sa.String(length=64), nullable=True),
    sa.Column('host', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('session', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('device', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('capabilities', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('capability_status', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('collector_errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('raw_observation', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('source_ip', sa.Text(), nullable=True),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('proxy_id', sa.Uuid(), nullable=True),
    sa.Column('computer_id', sa.Uuid(), nullable=True),
    sa.Column('physical_device_id', sa.Uuid(), nullable=True),
    sa.Column('media_state_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['computer_id'], ['computers.id'], ),
    sa.ForeignKeyConstraint(['media_state_id'], ['media_states.id'], ),
    sa.ForeignKeyConstraint(['physical_device_id'], ['physical_devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index(op.f('ix_observations_agent_id'), 'observations', ['agent_id'], unique=False)
    op.create_index('ix_observations_computer_id', 'observations', ['computer_id'], unique=False)
    op.create_index('ix_observations_hardware_stable_hash', 'observations', ['hardware_stable_sha256'], unique=False)
    op.create_index('ix_observations_hostname', 'observations', ['hostname'], unique=False)
    op.create_index('ix_observations_observed_at', 'observations', ['observed_at_utc'], unique=False)
    op.create_index('ix_observations_physical_device_id', 'observations', ['physical_device_id'], unique=False)
    op.create_index(op.f('ix_observations_proxy_id'), 'observations', ['proxy_id'], unique=False)
    op.create_index('ix_observations_user_sid', 'observations', ['user_sid'], unique=False)
    op.create_table('identity_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('observation_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('auto_linked', sa.Boolean(), nullable=False),
    sa.Column('candidate_physical_device_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_physical_device_id', sa.Uuid(), nullable=False),
    sa.Column('reasons', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('decided_at_utc', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_physical_device_id'], ['physical_devices.id'], ),
    sa.ForeignKeyConstraint(['candidate_physical_device_id'], ['physical_devices.id'], ),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('observation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('identity_decisions')
    op.drop_index('ix_observations_user_sid', table_name='observations')
    op.drop_index(op.f('ix_observations_proxy_id'), table_name='observations')
    op.drop_index('ix_observations_physical_device_id', table_name='observations')
    op.drop_index('ix_observations_observed_at', table_name='observations')
    op.drop_index('ix_observations_hostname', table_name='observations')
    op.drop_index('ix_observations_hardware_stable_hash', table_name='observations')
    op.drop_index('ix_observations_computer_id', table_name='observations')
    op.drop_index(op.f('ix_observations_agent_id'), table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_media_states_physical_device_id'), table_name='media_states')
    op.drop_table('media_states')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_expires_at_utc'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index('ix_audit_log_created_at', table_name='audit_log')
    op.drop_index('ix_audit_log_action', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_agents_last_seen_at_utc'), table_name='agents')
    op.drop_index(op.f('ix_agents_computer_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_physical_devices_hardware_stable_sha256'), table_name='physical_devices')
    op.drop_table('physical_devices')
    op.drop_table('computers')
    op.drop_table('auth_users')
    # ### end Alembic commands ###
