CREATE TABLE IF NOT EXISTS computers (
    id UUID PRIMARY KEY,
    computer_key VARCHAR(64) NOT NULL UNIQUE,
    hostname VARCHAR(255) NOT NULL,
    domain VARCHAR(255),
    first_seen_at TIMESTAMPTZ NOT NULL,
    last_seen_at TIMESTAMPTZ NOT NULL,
    last_host JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS physical_devices (
    id UUID PRIMARY KEY,
    hardware_stable_sha256 VARCHAR(64),
    status VARCHAR(32) NOT NULL,
    identity_confidence VARCHAR(32) NOT NULL,
    first_seen_at TIMESTAMPTZ NOT NULL,
    last_seen_at TIMESTAMPTZ NOT NULL,
    representative_device JSONB NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_physical_devices_hardware_stable_sha256
    ON physical_devices (hardware_stable_sha256);

CREATE TABLE IF NOT EXISTS media_states (
    id UUID PRIMARY KEY,
    physical_device_id UUID NOT NULL REFERENCES physical_devices(id),
    media_identity_sha256 VARCHAR(64),
    media_state_sha256 VARCHAR(64),
    first_seen_at TIMESTAMPTZ NOT NULL,
    last_seen_at TIMESTAMPTZ NOT NULL,
    representative_media JSONB NOT NULL,
    CONSTRAINT uq_media_state_device_hashes UNIQUE
        (physical_device_id, media_identity_sha256, media_state_sha256)
);

CREATE INDEX IF NOT EXISTS ix_media_states_physical_device_id
    ON media_states (physical_device_id);

CREATE TABLE IF NOT EXISTS observations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID NOT NULL UNIQUE,
    schema_version INTEGER NOT NULL,
    probe_version VARCHAR(64) NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    observed_at_utc TIMESTAMPTZ NOT NULL,
    received_at_utc TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    hostname VARCHAR(255),
    user_sid VARCHAR(255),
    hardware_stable_sha256 VARCHAR(64),
    pnp_observation_sha256 VARCHAR(64),
    media_identity_sha256 VARCHAR(64),
    media_state_sha256 VARCHAR(64),
    host JSONB NOT NULL,
    session JSONB NOT NULL,
    device JSONB NOT NULL,
    capabilities JSONB NOT NULL,
    capability_status JSONB NOT NULL,
    collector_errors JSONB NOT NULL,
    raw_observation JSONB NOT NULL,
    source_ip TEXT,
    agent_id UUID,
    proxy_id UUID,
    computer_id UUID REFERENCES computers(id),
    physical_device_id UUID REFERENCES physical_devices(id),
    media_state_id UUID REFERENCES media_states(id)
);

CREATE INDEX IF NOT EXISTS ix_observations_observed_at ON observations (observed_at_utc);
CREATE INDEX IF NOT EXISTS ix_observations_hostname ON observations (hostname);
CREATE INDEX IF NOT EXISTS ix_observations_user_sid ON observations (user_sid);
CREATE INDEX IF NOT EXISTS ix_observations_hardware_stable_hash ON observations (hardware_stable_sha256);
CREATE INDEX IF NOT EXISTS ix_observations_computer_id ON observations (computer_id);
CREATE INDEX IF NOT EXISTS ix_observations_physical_device_id ON observations (physical_device_id);
CREATE INDEX IF NOT EXISTS ix_observations_agent_id ON observations (agent_id);
CREATE INDEX IF NOT EXISTS ix_observations_proxy_id ON observations (proxy_id);

CREATE TABLE IF NOT EXISTS identity_decisions (
    id UUID PRIMARY KEY,
    observation_id BIGINT NOT NULL UNIQUE REFERENCES observations(id),
    result VARCHAR(32) NOT NULL,
    confidence DOUBLE PRECISION NOT NULL,
    auto_linked BOOLEAN NOT NULL,
    candidate_physical_device_id UUID REFERENCES physical_devices(id),
    assigned_physical_device_id UUID NOT NULL REFERENCES physical_devices(id),
    reasons JSONB NOT NULL,
    decided_at_utc TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS auth_users (
    id UUID PRIMARY KEY,
    username VARCHAR(128) NOT NULL UNIQUE,
    password_hash VARCHAR(512),
    role VARCHAR(32) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at_utc TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login_at_utc TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS auth_sessions (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth_users(id),
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    csrf_hash VARCHAR(64) NOT NULL,
    created_at_utc TIMESTAMPTZ NOT NULL,
    expires_at_utc TIMESTAMPTZ NOT NULL,
    last_seen_at_utc TIMESTAMPTZ NOT NULL,
    source_ip VARCHAR(128),
    user_agent VARCHAR(512)
);

CREATE INDEX IF NOT EXISTS ix_auth_sessions_user_id ON auth_sessions (user_id);
CREATE INDEX IF NOT EXISTS ix_auth_sessions_expires_at_utc ON auth_sessions (expires_at_utc);

CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth_users(id),
    username VARCHAR(128),
    action VARCHAR(128) NOT NULL,
    success BOOLEAN NOT NULL,
    source_ip VARCHAR(128),
    details JSONB NOT NULL,
    created_at_utc TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_audit_log_created_at ON audit_log (created_at_utc);
CREATE INDEX IF NOT EXISTS ix_audit_log_action ON audit_log (action);

CREATE TABLE IF NOT EXISTS agents (
    id UUID PRIMARY KEY,
    computer_id UUID REFERENCES computers(id),
    hostname VARCHAR(255) NOT NULL,
    domain VARCHAR(255),
    agent_version VARCHAR(64) NOT NULL,
    current_ips JSONB NOT NULL,
    queue_size INTEGER NOT NULL,
    selected_route VARCHAR(32) NOT NULL,
    proxy_id UUID,
    source_ip VARCHAR(128),
    token_hash VARCHAR(64),
    enroll_source_ip VARCHAR(128),
    enrolled_at_utc TIMESTAMPTZ,
    first_seen_at_utc TIMESTAMPTZ NOT NULL,
    last_seen_at_utc TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_agents_computer_id ON agents (computer_id);
CREATE INDEX IF NOT EXISTS ix_agents_last_seen_at_utc ON agents (last_seen_at_utc);
