CREATE TABLE IF NOT EXISTS observations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID NOT NULL UNIQUE,
    schema_version INTEGER NOT NULL,
    probe_version VARCHAR(64) NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    observed_at_utc TIMESTAMPTZ NOT NULL,
    received_at_utc TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    hostname VARCHAR(255),
    user_sid VARCHAR(255),
    hardware_evidence_sha256 VARCHAR(64),
    media_evidence_sha256 VARCHAR(64),
    observation_sha256 VARCHAR(64),
    host JSONB NOT NULL,
    session JSONB NOT NULL,
    device JSONB NOT NULL,
    capabilities JSONB NOT NULL,
    capability_status JSONB NOT NULL,
    collector_errors JSONB NOT NULL,
    raw_observation JSONB NOT NULL,
    source_ip TEXT
);

CREATE INDEX IF NOT EXISTS ix_observations_observed_at ON observations (observed_at_utc);
CREATE INDEX IF NOT EXISTS ix_observations_hostname ON observations (hostname);
CREATE INDEX IF NOT EXISTS ix_observations_user_sid ON observations (user_sid);
CREATE INDEX IF NOT EXISTS ix_observations_hardware_hash ON observations (hardware_evidence_sha256);

