ALTER TABLE agents ADD COLUMN IF NOT EXISTS token_hash VARCHAR(64);
ALTER TABLE agents ADD COLUMN IF NOT EXISTS enroll_source_ip VARCHAR(128);
ALTER TABLE agents ADD COLUMN IF NOT EXISTS enrolled_at_utc TIMESTAMPTZ;
